Update default.yaml

diff --git a/.github/workflows/default.yaml b/.github/workflows/default.yaml
--- a/.github/workflows/default.yaml
+++ b/.github/workflows/default.yaml
@@ -1,82 +1,54 @@
-# This is a basic workflow to help you get started with Actions
-
 name: CI
 
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the "master" branch
   push:
     branches: [ "master" ]
   pull_request:
     branches: [ "master" ]
-
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v3
-
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        run: |
-          echo Add other actions to build,
-          pwd
-          ls -alh
-          echo "lalala  ${{ vars.DOCKERHUB_REPO }}"
-      - name: Run Docker Build Script
+      
+      - name: Build Docker image
         env:
           DOCKER_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
           DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
           DOCKER_REPO: ${{ vars.DOCKERHUB_REPO }}
         run: |
-          chmod +x docker-build.sh
-          ./docker-build.sh
-  test:
-    # The type of runner that the job will run on
+          # Build the image
+          docker build -t $DOCKER_REPO:latest .
+          
+          # Login to DockerHub
+          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
+          
+          # Push the image
+          docker push $DOCKER_REPO:latest
+
+  validate:
+    needs: build  # This ensures validate runs after build
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v3
-
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Pull and run Docker image
+        env:
+          DOCKER_REPO: ${{ vars.DOCKERHUB_REPO }}
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
-  deploy:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v3
-
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          # Pull the image we just built
+          docker pull $DOCKER_REPO:latest
+          
+          # Run the container in detached mode, mapping port 80
+          docker run -d -p 80:80 --name web $DOCKER_REPO:latest
+          
+          # Wait a few seconds for Nginx to start
+          sleep 5
+          
+          # Test if index.html is accessible
+          if curl -f http://localhost/index.html; then
+            echo "Successfully validated index.html is accessible"
+          else
+            echo "Failed to access index.html"
+            exit 1
+          fi
